# Generated by Django 5.1.4 on 2026-08-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.TextField()),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        default="fa-solid fa-star",
                        help_text="Example: fa-solid fa-gem",
                        max_length=100,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("features", models.TextField(help_text="Enter one feature per line")),
                (
                    "badge",
                    models.CharField(
                        blank=True,
                        help_text="Example: Most Popular",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
    ]
