# Generated by Django 5.1.4 on 2026-08-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.RemoveField(
            model_name="service",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="service",
            name="badge",
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="features",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.CharField(default="fa-solid fa-star", max_length=100),
        ),
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                ("date_of_birth", models.DateField()),
                ("time_of_birth", models.TimeField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("birth_place", models.CharField(max_length=200)),
                ("consultation_date", models.DateField(blank=True, null=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Hindi", "Hindi"),
                            ("English", "English"),
                            ("Punjabi", "Punjabi"),
                        ],
                        default="English",
                        max_length=20,
                    ),
                ),
                ("question", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="myapp.service",
                    ),
                ),
            ],
        ),
    ]
