# Generated by Django 5.1.4 on 2026-08-11 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_pricingplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="myapp.pricingplan",
            ),
            preserve_default=False,
        ),
    ]
